const data = {
    products: [
        {
            _id: '1',
            name: 'Slim Shirt',
            image: '/images/p1.jpg',
            price: 60,
            brand: 'D&G',
            rating: 1.2,
            numReviews: 298,
            countInStock: 7,
            description: 'High quality product',
        },
        {
            _id: '2',
            name: 'Slim Shirt',
            image: '/images/p2.jpg',
            price: 160,
            brand: 'Nike',
            rating: 2.8,
            numReviews: 544,
            countInStock: 57,
            description: 'High quality product',
        },
        {
            _id: '3',
            name: 'Slim Shirt',
            image: '/images/p3.jpg',
            price: 118,
            brand: 'Ralph lauren',
            rating: 4.2,
            numReviews: 2151,
            countInStock: 54,
            description: 'High quality product',
        },
        {
            _id: '4',
            name: 'Slim Shirt',
            image: '/images/p4.jpg',
            price: 51,
            brand: 'Nike',
            rating: 2.6,
            numReviews: 456,
            countInStock: 98,
            description: 'High quality product',
        },
        {
            _id: '5',
            name: 'Slim Shirt',
            image: '/images/p5.jpg',
            price: 85,
            brand: 'Nike',
            rating: 1.9,
            numReviews: 254,
            countInStock: 2,
            description: 'High quality product',
        },
        {
            _id: '6',
            name: 'Slim Shirt',
            image: '/images/p6.jpg',
            price: 38,
            brand: 'Nike',
            rating: 3.2,
            numReviews: 654,
            countInStock: 21,
            description: 'High quality product',
        },
        {
            _id: '7',
            name: 'Slim Shirt',
            image: '/images/p7.jpg',
            price: 21,
            brand: 'Nike',
            rating: 1.5,
            numReviews: 2,
            countInStock: 0,
            description: 'High quality product',
        }
    ]
}

export default data;